export default [
  'event AdminChanged(address previousAdmin, address newAdmin)',
  'event BeaconUpgraded(address indexed beacon)',
  'event Upgraded(address indexed implementation)',
  'function admin() returns (address admin_)',
  'function changeAdmin(address newAdmin)',
  'function implementation() returns (address implementation_)',
  'function upgradeTo(address newImplementation)',
  'function upgradeToAndCall(address newImplementation, bytes data) payable',
  'event Claimed(uint256 indexed index, address indexed sender, uint256 amount0, uint256 txFee)',
  'event Created(uint256 indexed index, address indexed sender, tuple(address creator, address token0, address token1, uint256 amountTotal0, uint256 amountTotal1, uint48 openAt, uint48 closeAt, uint48 claimAt) pool, string name, bytes32 whitelistRoot)',
  'event Initialized(uint8 version)',
  'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
  'event Swapped(uint256 indexed index, address indexed sender, uint256 amount0, uint256 amount1, uint256 txFee)',
  'event UserClaimed(uint256 indexed index, address indexed sender, uint256 amount0)',
  'function amountSwap0P(uint256) view returns (uint256)',
  'function amountSwap1P(uint256) view returns (uint256)',
  'function create(tuple(string name, address token0, address token1, uint256 amountTotal0, uint256 amountTotal1, uint48 openAt, uint48 closeAt, uint48 claimAt, uint256 maxAmount1PerWallet, bytes32 whitelistRoot) poolReq, bytes signature)',
  'function creatorClaim(uint256 index)',
  'function creatorClaimed(address, uint256) view returns (bool)',
  'function filledAtP(uint256) view returns (uint256)',
  'function getPoolCount() view returns (uint256)',
  'function initialize(uint256 _txFeeRatio, address _stakeContract, address _signer)',
  'function maxAmount1PerWalletP(uint256) view returns (uint256)',
  'function myAmountSwapped0(address, uint256) view returns (uint256)',
  'function myAmountSwapped1(address, uint256) view returns (uint256)',
  'function myClaimed(address, uint256) view returns (bool)',
  'function owner() view returns (address)',
  'function pools(uint256) view returns (address creator, address token0, address token1, uint256 amountTotal0, uint256 amountTotal1, uint48 openAt, uint48 closeAt, uint48 claimAt)',
  'function renounceOwnership()',
  'function setSigner(address signer_)',
  'function signer() view returns (address)',
  'function stakeContract() view returns (address)',
  'function swap(uint256 index, uint256 amount1, bytes32[] proof) payable',
  'function transferOwnership(address newOwner)',
  'function txFeeP(uint256) view returns (uint256)',
  'function txFeeRatio() view returns (uint256)',
  'function userClaim(uint256 index)',
  'function whitelistRootP(uint256) view returns (bytes32)',
  'constructor(address _logic, address admin_, bytes _data) payable',
]
